#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.pancm.domain
  mapperLocations: classpath:mybatis/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://116.62.145.113:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

